### ISSUE TITLE
Show regular news on frontpage

### ISSUE THREAD

**Issue by lsolesen** [vih/vies-build#1]
Slider with news back on the frontpage.

**Comment by lsolesen** [comment]
![vies-news-tickler](https://cloud.githubusercontent.com/assets/148026/6413364/f96893ae-be8e-11e4-9abd-636bf1ed553a.png)

There should be a news tickler with coloured background which shows the latest news (configurable through pane settings).

**Comment by mglaman** [comment]
@lsolesen configurable means the background color, correct? Not news items in an entity queue?

**Comment by lsolesen** [comment]
No it should just be the most recent news showing with the headline. It should have a coloured background decided by the theme (should not be configurable). Configurable means how many items I want to show.

**Comment by mglaman** [comment]
@lsolesen ok cool. And by ticker.. so you mean it should scroll or just a regular list of the titles and pane configuration allows you to change limit

**Comment by mglaman** [comment]
Also.. Should a vies_news repo be made for a News feature? Or somewhere to export the View to?

**Comment by lsolesen** [comment]
Scroll. Showing one at a time like

```
Ny news item / see All news
```

You can decide whehter there should be a vies_news repo. Whatever, is the best way to do it in your opinion :)

**Comment by mglaman** [comment]
I think for now putting the View in vies_deploy for right now until things flush out a bit more - just as a regular Views export without Features. That way it can be accessed on the production site and added (since front page can't really be exported due to Fieldable Panels Panes [yet])

**Comment by mglaman** [comment]
Tagging vih/ketsjup-theme@c70d65a7412e2c7fe71cbe0ebd7113e315a71d0d

**Comment by mglaman** [comment]
@lsolesen don't have access to vies_deploy to push exported view

**Comment by lsolesen** [comment]
This can be closed as soon as a return has been added to the view.
