### ISSUE TITLE
Add a little tint to the header

### ISSUE THREAD

**Issue by lsolesen** [vih/vies-build#11]
To make the layout a little nicer the topbar could have a little tint going from a darker orange to a lighter one (a little like vih.dk).

![skaermbillede 2015-03-16 kl 17 03 02](https://cloud.githubusercontent.com/assets/148026/6670539/6fa7caf8-cbff-11e4-9161-a9c967b4e6a9.png)

**Comment by cornifex** [comment]
Fixed by vih/ketsjup-theme@0abb1a7

**Comment by cornifex** [comment]
![screenshot from 2015-03-18 19 34 51](https://cloud.githubusercontent.com/assets/7952198/6722372/bb581572-cda6-11e4-8501-52d6800a7caf.png)
