### ISSUE TITLE
Cannot save links on frontpage

### ISSUE THREAD

**Issue by lsolesen** [vih/vies-build#14]
On http://vies.dk it is impossible to change the links for:

![skaermbillede 2015-05-20 kl 12 57 32](https://cloud.githubusercontent.com/assets/148026/7724246/2c98200e-fef0-11e4-9094-43dcfeefcd59.png)

**Comment by lsolesen** [comment]
It just keeps setting it to 1 for the Url ("Sti")

![skaermbillede 2015-05-20 kl 12 59 08](https://cloud.githubusercontent.com/assets/148026/7724253/5c88a5f4-fef0-11e4-9616-07f320885da2.png)

**Comment by mglaman** [comment]
I wonder if its something with the pane's themselves - maybe delete and re-add them. Tested with manual add of an image pane locally without issue. Did not try with local copy of database.

**Comment by lsolesen** [comment]
@mglaman suggested that I try to delete the panes and readd them.

**Comment by lsolesen** [comment]
@mglaman Tried adding another pane, and the same problem persists. The URL is not saved correctly.

**Comment by mglaman** [comment]
In progress

**Comment by mglaman** [comment]
Local host finally threw some errors: Warning: strpos() expects parameter 1 to be string, array given i url() (linje 2226 af /var/www/vies.dk/includes/common.inc).

**Comment by mglaman** [comment]
The link isn't properly being sent.

![screen shot 2015-07-09 at 9 22 29 am](https://cloud.githubusercontent.com/assets/3698644/8597595/11ef61d8-261c-11e5-9f9e-89d5e4e36777.png)

**Comment by lsolesen** [comment]
For the 'billeder'-pane the problem might be that the page is not a node, but a landing page?

**Comment by lsolesen** [comment]
Strange, because it works in the preview.

**Comment by lsolesen** [comment]
@mglaman Any news on this one?

**Comment by lsolesen** [comment]
@mglaman Any chance you can look into this again, as it is not just on the frontpage, but on all headlines - see e.g. https://vies.dk/fag/atletik and try to add a link to "Se nyheder fra atletiklinjen" - as reported in gh-32

**Comment by lsolesen** [comment]
@dinadk I think something broke on previous versions of the site. Today I was able to create new entities, and now the links seems to be fixed both on the frontpage and on the subjects. If you encounter other instances, you need to delete the pane which is not working and create a new pane.
