### ISSUE TITLE
Facilites should look nicer

### ISSUE THREAD

**Issue by lsolesen** [vih/vies-build#17]
It looks like this now:

![skaermbillede 2015-06-18 kl 06 31 21](https://cloud.githubusercontent.com/assets/148026/8224231/f209e1f2-1583-11e5-9cef-135d0ae3fc17.png)

I could look a little more like (larger font and an arrow):

![skaermbillede 2015-06-18 kl 06 31 34](https://cloud.githubusercontent.com/assets/148026/8224233/fbc19af0-1583-11e5-955c-cb65a3f39b35.png)

**Comment by mglaman** [comment]
![screenshot from 2015-07-28 21 46 50](https://cloud.githubusercontent.com/assets/3698644/8948916/2eae6ef8-3572-11e5-9b7f-e6a887cc1ddd.png)

Incoming result
