### ISSUE TITLE
Submenu - submenu is not opening automatically

### ISSUE THREAD

**Issue by lsolesen** [vih/vies-build#19]
See e.g. Om Os --> Personale should open up a sub menu.

![skaermbillede 2015-07-01 kl 09 19 41](https://cloud.githubusercontent.com/assets/148026/8449526/67bcd500-1fd2-11e5-8661-3eb64adf3bc2.png)

**Comment by mglaman** [comment]
Linking to #5. I feel like Radix+Bootstrap made some really big changes around dropdowns.
