### ISSUE TITLE
Make it possible to rearrange employees

### ISSUE THREAD

**Issue by lsolesen** [vih/vies-build#3]
https://github.com/vih/vies_employees/issues/1

Should probably be done with draggableviews?

**Comment by lsolesen** [comment]
Committed to vies-build also: https://github.com/vih/vies-build/commit/019023f805cf97e63dd0af01c8147d98d359c433

**Comment by lsolesen** [comment]
Rearrange employees at http://vies.dk/admin/content/employees

**Comment by lsolesen** [comment]
@dinadk Now it should work for editors also.

**Comment by dinadk** [comment]
Hmm, har nu prøvet, og kan også godt rykke rundt, når jeg kommer til linket, men det virker ikke..

Fra: Lars Olesen [mailto:notifications@github.com]
Sendt: 11. april 2016 15:44
Til: vih/vies-build vies-build@noreply.github.com
Emne: Re: [vih/vies-build] Make it possible to rearrange employees (#3)

Rearrange employees at http://vies.dk/admin/content/employees

**Comment by lsolesen** [comment]
Clicked on save also?

Den tor. 14. apr. 2016 10.26 skrev dinadk notifications@github.com:
