### ISSUE TITLE
Submenu not working correctly on subpages

### ISSUE THREAD

**Issue by lsolesen** [vih/vies-build#5]
https://vies.dk/boglig-struktur

This is how it is supposed to be

![skaermbillede 2015-03-16 kl 16 56 25](https://cloud.githubusercontent.com/assets/148026/6670151/753c3d48-cbfd-11e4-9b53-fecb801fea1b.png)

This is how it is - no submenu expanding until you click on the submenu (but you cannot see that you can click the submenu)

![skaermbillede 2015-03-16 kl 16 56 16](https://cloud.githubusercontent.com/assets/148026/6670168/84a02664-cbfd-11e4-90c1-925f0f145e19.png)

**Comment by lsolesen** [comment]
Also the submenu in the top works a little strange. The submenu appears under instead of expanding sideways.

![skaermbillede 2015-03-16 kl 16 58 35](https://cloud.githubusercontent.com/assets/148026/6670230/c6dfaa90-cbfd-11e4-8594-230d1fb8a367.png)

**Comment by lsolesen** [comment]
@cornifex Should @mglaman fix this?

**Comment by mglaman** [comment]
@lsolesen I got a fix up that auto expands the sidebar menu, not sure how to get it back to being on the right side. Looks like Bootstrap changed how they do things, will keep investigating.
