### ISSUE TITLE
Rounded corners for images

### ISSUE THREAD

**Issue by lsolesen** [vih/vies-build#7]
In the old theme the corners looked like this:

![skaermbillede 2015-03-16 kl 17 02 17](https://cloud.githubusercontent.com/assets/148026/6670328/428eb654-cbfe-11e4-85a3-6a9328c3a53e.png)

This was a default on Radix I think. But I liked it.

**Comment by cornifex** [comment]
@lsolesen What images should have rounded corners? Just node featured images, or images in specific node types, views, etc?

**Comment by lsolesen** [comment]
Pretty much all images.
