### ISSUE TITLE
It is not possible to expand menu on mobile

### ISSUE THREAD

**Issue by lsolesen** [vih/vies-build#9]
When clicking a parent item in the navbar menu, I am transferred directly to the menu item. That makes it impossible to navigate to subitems on mobile.

**Comment by cornifex** [comment]
The dropdowns toggle when the caret is clicked now but the page still directs to the anchor's href. During testing, I was able to move the caret outside of the anchor tag, but then toggling stopped working. This will take a bit more debugging.

**Comment by lsolesen** [comment]
@cornifex How close are you to fixing this?

**Comment by mglaman** [comment]
@lsolesen this looks to be fixed? Maybe Radix worked it out itself.
